# JUCE 7.0.10's AudioProcessor state callbacks return void. Keep failure inside
# the VST3 ABI and return its error result before writing any saved-state bytes.
# Generate a player-only wrapper, leaving the pinned JUCE submodule untouched.
get_target_property(stateWrapperSources juce_audio_plugin_client_VST3 INTERFACE_SOURCES)
set(stateWrapperOriginal "${JUCE_MODULES_DIR}/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp")
foreach(wrapperSource IN LISTS stateWrapperSources)
	if(wrapperSource MATCHES "juce_audio_plugin_client_VST3.cpp$")
		set(stateWrapperOriginal "${wrapperSource}")
	endif()
endforeach()
file(READ "${stateWrapperOriginal}" stateWrapperText)
set(stateWrapperGet "tresult PLUGIN_API getState (IBStream* state) override\n    {")
set(stateWrapperSet "tresult PLUGIN_API setState (IBStream* state) override\n    {")
set(stateWrapperGetEnd "return state->write (mem.getData(), (Steinberg::int32) mem.getSize());\n    }")
set(stateWrapperSetEnd "return kResultFalse;\n    }\n\n   #if JUCE_VST3_CAN_REPLACE_VST2")
foreach(anchor IN ITEMS stateWrapperGet stateWrapperSet stateWrapperGetEnd stateWrapperSetEnd)
	string(FIND "${stateWrapperText}" "${${anchor}}" anchorPosition)
	if(anchorPosition EQUAL -1)
		message(FATAL_ERROR "JUCE VST3 state wrapper changed; review exception boundary: ${anchor}")
	endif()
endforeach()
string(REPLACE "${stateWrapperGet}" "tresult PLUGIN_API getState (IBStream* state) override try\n    {" stateWrapperText "${stateWrapperText}")
string(REPLACE "${stateWrapperSet}" "tresult PLUGIN_API setState (IBStream* state) override try\n    {" stateWrapperText "${stateWrapperText}")
string(REPLACE "${stateWrapperGetEnd}" "${stateWrapperGetEnd}\n    catch (...) { return kInternalError; }" stateWrapperText "${stateWrapperText}")
string(REPLACE "${stateWrapperSetEnd}" "return kResultFalse;\n    }\n    catch (...) { return kInternalError; }\n\n   #if JUCE_VST3_CAN_REPLACE_VST2" stateWrapperText "${stateWrapperText}")
set(stateWrapperGenerated "${CMAKE_CURRENT_BINARY_DIR}/Emu88Vst3StateBoundary.cpp")
if(EXISTS "${stateWrapperGenerated}")
	file(READ "${stateWrapperGenerated}" stateWrapperPrevious)
endif()
if(NOT "${stateWrapperPrevious}" STREQUAL "${stateWrapperText}")
	file(WRITE "${stateWrapperGenerated}" "${stateWrapperText}")
endif()

add_library(88emuVst3StateBoundary INTERFACE)
foreach(property IN ITEMS INTERFACE_COMPILE_DEFINITIONS INTERFACE_COMPILE_FEATURES
	INTERFACE_COMPILE_OPTIONS INTERFACE_INCLUDE_DIRECTORIES INTERFACE_LINK_LIBRARIES INTERFACE_LINK_OPTIONS)
	get_target_property(value juce_audio_plugin_client_VST3 ${property})
	if(value)
		set_property(TARGET 88emuVst3StateBoundary PROPERTY ${property} "${value}")
	endif()
endforeach()
list(REMOVE_ITEM stateWrapperSources "${stateWrapperOriginal}")
target_sources(88emuVst3StateBoundary INTERFACE ${stateWrapperSources} "${stateWrapperGenerated}")
get_target_property(wrapperLinks 88emuplayer_VST3 LINK_LIBRARIES)
list(REMOVE_ITEM wrapperLinks juce::juce_audio_plugin_client_VST3)
list(APPEND wrapperLinks 88emuVst3StateBoundary)
set_property(TARGET 88emuplayer_VST3 PROPERTY LINK_LIBRARIES "${wrapperLinks}")
